using System.Collections.Concurrent;
using HarmonyLib;

namespace StardewUI;

internal static class Logger
{
    public static readonly bool IsMainThread = true;

#if DEBUG
    private const LogLevel DEFAULT_LOG_LEVEL = LogLevel.Debug;
#else
    private const LogLevel DEFAULT_LOG_LEVEL = LogLevel.Trace;
#endif

    internal static IMonitor? Monitor;
    private static ConcurrentQueue<(string, LogLevel, bool)> logQueue = new();

    /// <inheritdoc cref="IMonitor.Log(string, LogLevel)"/>
    public static void Log(string message, LogLevel level = DEFAULT_LOG_LEVEL)
    {
        if (UI.IsMainThread)
        {
            ConsumeQueue();
            Monitor?.Log(message, level);
        }
        else
        {
            logQueue.Enqueue(new(message, level, false));
        }
    }

    /// <inheritdoc cref="IMonitor.LogOnce(string, LogLevel)"/>
    public static void LogOnce(string message, LogLevel level = DEFAULT_LOG_LEVEL)
    {
        if (UI.IsMainThread)
        {
            ConsumeQueue();
            Monitor?.LogOnce(message, level);
        }
        else
        {
            logQueue.Enqueue(new(message, level, true));
        }
    }

    // Any logs generated by non main thread is only actually logged once back on main thread
    // This is a silly way to do it but shrug the actual fix is better done on SMAPI monitor side
    private static void ConsumeQueue()
    {
        while (logQueue.TryDequeue(out (string, LogLevel, bool) logEntry))
        {
            if (logEntry.Item3)
            {
                Monitor?.LogOnce(logEntry.Item1, logEntry.Item2);
            }
            else
            {
                Monitor?.Log(logEntry.Item1, logEntry.Item2);
            }
        }
    }
}
